#!/bin/sh
# Regenerate the tables and figures from results/.
# A failing step is reported as a failure and the script exits non-zero.
export PYTHONPATH=$PWD/src:$PWD/experiments:$PWD/figures:$PYTHONPATH
command -v python >/dev/null 2>&1 || { echo "ERROR: no 'python' on PATH. Create and activate the virtualenv first (see README), or put python3 on PATH as python."; exit 127; }
fail=0
t=$(mktemp); trap 'rm -f "$t"' EXIT
echo "-- inflating compressed result files"; for f in $(find results -name "*.csv.gz"); do gunzip -kf "$f"; done
echo "-- bound figure"; if ( python experiments/fig_bound.py ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: bound figure -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: bound figure"; fail=1; fi; fi
echo "-- regimes table and macros"; if ( cd figures && python make_regimes_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: regimes table and macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: regimes table and macros"; fail=1; fi; fi
echo "-- control-generator table and figure"; if ( cd figures && python make_simcontrol_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: control-generator table and figure -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: control-generator table and figure"; fail=1; fi; fi
echo "-- dose-response table and macros"; if ( cd figures && python make_gendesign_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: dose-response table and macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: dose-response table and macros"; fail=1; fi; fi
echo "-- MIMIC-IV replication macros"; if ( cd figures && python make_p3mimic_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: MIMIC-IV replication macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: MIMIC-IV replication macros"; fail=1; fi; fi
echo "-- diagnostic validation macros"; if ( cd figures && python make_diagval_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: diagnostic validation macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: diagnostic validation macros"; fail=1; fi; fi
[ "$fail" -eq 0 ] || { echo; echo "reproduce.sh: one or more steps FAILED (see above)."; exit 1; }
echo; echo "reproduce.sh: no step failed."
