"""Emit tables/simcontrol.tex and tables/simcontrol_counts.tex from the committed SIMCONTROL results.

Nothing in the paper's control paragraph is typed by hand. Run from the paper directory:
    ../paper-plco-hypergraph/.venv/bin/python figures/make_simcontrol_table.py
"""
import glob, pathlib, numpy as np, pandas as pd

SRC = pathlib.Path(__file__).resolve().parents[1] / "results" / "simcontrol"
OUT = pathlib.Path(__file__).resolve().parents[1] / "tables"

d = pd.concat([pd.read_csv(f) for f in sorted(glob.glob(str(SRC / "*.csv")))], ignore_index=True)
g = d.pivot_table(index="het", columns="outcome_from", values="delta_vs_tuned_ind", aggfunc="mean")
sp = d.pivot_table(index="het", columns="outcome_from", values="coef_spread", aggfunc="mean")

with open(OUT / "simcontrol.tex", "w") as f:
    f.write("% generated by figures/make_simcontrol_table.py -- do not edit\n")
    f.write("\\begin{tabular}{rrrr}\n\\toprule\n")
    f.write("slope heterogeneity & coefficient spread & standard generator & control \\\\\n\\midrule\n")
    for h in sorted(g.index):
        f.write(f"${h:.1f}$ & ${sp.loc[h,'pattern']:.4f}$ & "
                f"${g.loc[h,'pattern']:+.4f}$ & ${g.loc[h,'shared']:+.4f}$ \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")

p, s = d[d.outcome_from == "pattern"], d[d.outcome_from == "shared"]
hi = max(g.index)
vals = [("ScCells", len(p)),
        ("ScStdHi", f"{g.loc[hi,'pattern']:+.4f}"), ("ScCtrlHi", f"{g.loc[hi,'shared']:+.4f}"),
        ("ScCtrlLo", f"{g.loc[min(g.index),'shared']:+.4f}"),
        ("ScSpreadHi", f"{sp.loc[hi,'pattern']:.4f}"),
        ("ScStdMean", f"{p.delta_vs_tuned_ind.mean():+.4f}"),
        ("ScStdMax", f"{p.delta_vs_tuned_ind.max():+.4f}"),
        ("ScStdWins", int((p.p_vs_tuned_ind < 0.05).sum())),
        ("ScCtrlWins", int((s.p_vs_tuned_ind < 0.05).sum())),
        ("ScCtrlMean", f"{s.delta_vs_tuned_ind.mean():+.4f}"),
        ("ScCtrlMax", f"{s.delta_vs_tuned_ind.max():+.4f}"),
        ("ScMarStd", f"{d[(d.mechanism=='MAR')&(d.het==hi)&(d.outcome_from=='pattern')].delta_vs_tuned_ind.mean():+.4f}"),
        ("ScMarCtrl", f"{d[(d.mechanism=='MAR')&(d.het==hi)&(d.outcome_from=='shared')].delta_vs_tuned_ind.mean():+.4f}")]
with open(OUT / "simcontrol_counts.tex", "w") as f:
    f.write("% generated by figures/make_simcontrol_table.py -- do not edit\n")
    for k, v in vals: f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(f"simcontrol.tex ({len(g)} rows); simcontrol_counts.tex ({len(vals)} macros)")
for k, v in vals: print(f"  {k:12s} {v}")

# --- the same result as a figure, which is how it reads best ---
FOUT = OUT / "fig_simcontrol.tex"
g = d.pivot_table(index="het", columns="outcome_from", values="delta_vs_tuned_ind", aggfunc="mean")
e = d.pivot_table(index="het", columns="outcome_from", values="delta_vs_tuned_ind", aggfunc="sem")
sp = d.pivot_table(index="het", columns="outcome_from", values="coef_spread", aggfunc="mean")
mech = d[d.het == max(g.index)].pivot_table(index="mechanism", columns="outcome_from",
                                            values="delta_vs_tuned_ind", aggfunc="mean")
pts = lambda idx, v, s: " ".join(f"({x:.2f},{v[x]:.4f}) +- (0,{s[x]:.4f})" for x in idx)
L = [r"% generated by figures/make_simcontrol_table.py -- do not edit",
     r"\begin{tikzpicture}",
     r"\begin{axis}[name=A, width=0.46\textwidth, height=3.9cm,",
     r"  xlabel={heterogeneity (spread below)},",
     r"  ylabel={gain}, xtick={0,0.5,1.5},",
     r"  xticklabels={$0$\\{\tiny$0.00$},$0.5$\\{\tiny$0.48$},$1.5$\\{\tiny$1.44$}},",
     r"  xticklabel style={align=center}, ymin=-0.004,",
     r"  title={\textbf{A}\quad Both generators}, title style={font=\small, at={(0,1.02)},",
     r"  anchor=south west}, label style={font=\small}, tick label style={font=\small},",
     r"  legend style={font=\scriptsize, draw=none, fill=none, at={(0.5,-0.62)},",
     r"  anchor=north, legend columns=1}, axis lines=left, error bars/y dir=both,",
     r"  error bars/y explicit]"]
for col, opt, lab in [("pattern", r"mark=*, thick, color=hgblue, mark options={solid}", "outcome from the pattern's own coefficients"),
                      ("shared", r"mark=square*, thick, dashed, color=hggrey, mark options={solid}", "outcome from a shared vector (control)")]:
    L.append(r"\addplot[" + opt + r"] coordinates {" + pts(g.index, g[col], e[col]) + r"};")
    L.append(r"\addlegendentry{" + lab + r"}")
L += [r"\end{axis}",
      r"\begin{axis}[name=B, at={($(A.east)+(1.8cm,0)$)}, anchor=west, width=0.36\textwidth,",
      r"  height=3.9cm, ybar=2pt, bar width=7pt, xlabel={mechanism},",
      r"  ylabel={gain (log)}, symbolic x coords={MCAR,MAR,MNAR}, xtick=data,",
      r"  ymode=log, ymin=5e-5, ymax=0.2, log origin=infty,",
      r"  title={\textbf{B}\quad By mechanism}, title style={font=\small, at={(0,1.02)},",
      r"  anchor=south west}, label style={font=\small}, tick label style={font=\small},",
      r"  legend style={font=\scriptsize, draw=none, fill=none, at={(0.5,-0.62)},",
      r"  anchor=north, legend columns=2}, axis lines=left]"]
for col, opt, lab in [("pattern", r"fill=hgblue, draw=hgblue", "pattern"),
                      ("shared", r"fill=hgamber, draw=hgblue", "control")]:
    L.append(r"\addplot[" + opt + r"] coordinates {" +
             " ".join(f"({m},{mech.loc[m,col]:.4f})" for m in ("MCAR","MAR","MNAR")) + r"};")
    L.append(r"\addlegendentry{" + lab + r"}")
L += [r"\end{axis}", r"\end{tikzpicture}"]
FOUT.write_text("\n".join(L) + "\n")
print(f"wrote {FOUT.name}")
