"""Emit tables/diagval_counts.tex: the diagnostic validation on the synthetic factorial.

Paper 1 and the heterogeneity paper both quoted these numbers as typed literals (AUC 0.757,
Spearman +0.51, ...). They now come from results/diagnostic_validation.csv, which
experiments/validate_diagnostic.py writes from the synthetic suite. Written 2026-09-23 for
SYNTHRERUN (prereg/SYNTHRERUN.md), which re-ran that suite under current code on Linux.

"Significant win" is the definition both papers use: delta > 0 against the tuned indicator
model at Wilcoxon p < 0.05. "Any win" is delta > 0, which the heterogeneity paper also reports.
AUC is the Mann-Whitney statistic over the two groups.
"""
import pathlib
import sys

import pandas as pd
from scipy import stats

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "results" / (sys.argv[1] if len(sys.argv) > 1 else "diagnostic_validation.csv")
OUT = HERE.parent / "tables" / "diagval_counts.tex"

d = pd.read_csv(SRC)
won = (d.delta > 0) & (d.p < 0.05)
anyw = d.delta > 0


def auc(col, m):
    return stats.mannwhitneyu(d.loc[m, col], d.loc[~m, col]).statistic / (m.sum() * (~m).sum())


def sci(p, sig):
    """p as LaTeX a\\times10^{b}, with `sig` significant figures."""
    m, e = f"{p:.{sig - 1}e}".split("e")
    return f"{m}\\times10^{{{int(e)}}}"


d["combo"] = d.het_excess * d.cov30
rho = stats.spearmanr(d.het_excess, d.delta)
rho_i = stats.spearmanr(d.iota, d.delta)
vals = [
    ("DvConfigs", f"{len(d)}"), ("DvWins", f"{int(won.sum())}"), ("DvRest", f"{int((~won).sum())}"),
    ("DvRho", f"{rho.statistic:+.2f}"), ("DvRhoFine", f"{rho.statistic:+.3f}"),
    ("DvRhoP", sci(rho.pvalue, 1)), ("DvRhoPFine", sci(rho.pvalue, 2)),
    ("DvAuc", f"{auc('het_excess', won):.3f}"),
    ("DvWinMean", f"{d.loc[won, 'het_excess'].mean():+.3f}"),
    ("DvRestMean", f"{d.loc[~won, 'het_excess'].mean():+.3f}"),
    ("DvIotaAuc", f"{auc('iota', won):.3f}"), ("DvCovAuc", f"{auc('cov30', won):.3f}"),
    ("DvComboAuc", f"{auc('combo', won):.3f}"),
    ("DvAnyWins", f"{int(anyw.sum())}"), ("DvAnyAuc", f"{auc('het_excess', anyw):.3f}"),
    ("DvIotaAnyAuc", f"{auc('iota', anyw):.3f}"),
    ("DvIotaRho", f"{rho_i.statistic:+.3f}"), ("DvIotaP", sci(rho_i.pvalue, 2)),
]
with open(OUT, "w") as f:
    f.write(f"% generated by figures/make_diagval_table.py from results/{SRC.name} -- do not edit\n")
    for k, v in vals:
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(f"{OUT.name} written ({len(vals)} macros) from {SRC.name}")
for k, v in vals:
    print(f"  {k:12s} {v}")
