"""Emit tables/regimes.tex and tables/regimes_counts.tex: the two-regimes contrast.

These eight numbers were typed by hand until 2026-09-15 and are now generated. They were briefly
recorded as not reproducing, which was wrong: the error was reading `safe_adaptive` minus a
baseline column instead of the precomputed per-cell paired deltas the caption refers to
(`delta_vs_tuned_ind` for the factorial, `delta` for the real suite). Both reproduce exactly.

Run from the paper directory:
    ../paper-plco-hypergraph/.venv/bin/python figures/make_regimes_table.py
"""
import pathlib, pandas as pd

SRC = pathlib.Path(__file__).resolve().parents[1] / "results"
OUT = pathlib.Path(__file__).resolve().parents[1] / "tables"

s = pd.read_csv(SRC / "synthetic_suite_1se.csv")
r = pd.read_csv(SRC / "real_suite.csv")
sd, sp = s.delta_vs_tuned_ind, s.p_vs_tuned_ind
rd, rp = r.delta, r.p

rows = [("mean gain over tuned baseline", f"{sd.mean():+.4f}", f"{rd.mean():+.4f}"),
        ("largest gain observed",         f"{sd.max():+.4f}",  f"{rd.max():+.4f}"),
        ("significant wins",   str(int(((sd > 0) & (sp < 0.05)).sum())),
                               "\\textbf{" + str(int(((rd > 0) & (rp < 0.05)).sum())) + "}"),
        ("significant losses", str(int(((sd < 0) & (sp < 0.05)).sum())),
                               "\\textbf{" + str(int(((rd < 0) & (rp < 0.05)).sum())) + "}")]
with open(OUT / "regimes.tex", "w") as f:
    f.write("% generated by figures/make_regimes_table.py -- do not edit\n")
    f.write("\\begin{tabular}{lrr}\n\\toprule\n")
    f.write(f" & simulation ({len(s)} cells) & real data ({len(r)} datasets) \\\\\n\\midrule\n")
    for lab, a, b in rows:
        f.write(f"{lab} & ${a}$ & ${b}$ \\\\\n" if "textbf" not in b
                else f"{lab} & ${a}$ & {b} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")

vals = [("RgCells", len(s)), ("RgData", len(r)),
        ("RgSimMean", f"{sd.mean():+.4f}"), ("RgRealMean", f"{rd.mean():+.4f}"),
        ("RgSimMax", f"{sd.max():+.4f}"), ("RgRealMax", f"{rd.max():+.4f}"),
        ("RgSimWins", int(((sd > 0) & (sp < 0.05)).sum())),
        ("RgRealWins", int(((rd > 0) & (rp < 0.05)).sum())),
        ("RgRealLoss", int(((rd < 0) & (rp < 0.05)).sum())),
        ("RgRatio", f"{sd.max() / rd.max():.0f}")]
with open(OUT / "regimes_counts.tex", "w") as f:
    f.write("% generated by figures/make_regimes_table.py -- do not edit\n")
    for k, v in vals:
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(f"regimes.tex and regimes_counts.tex written ({len(vals)} macros)")
print(f"  simulation mean {sd.mean():+.4f} max {sd.max():+.4f}; real mean {rd.mean():+.4f} max {rd.max():+.4f}")
