"""Emit tables/p3mimic.tex from the committed P3MIMIC results (prereg/P3MIMIC.md).

The table said "GENERATED" from its first commit, but no script wrote it: the macros were
typed from the scorer's output. This reproduces every one of them exactly, and adds the
permutation-seed spread of het_excess that the text quotes, from results/p3mimic_hexc_seeds.csv
(experiments/p3mimic_hexc_seeds.py). Written 2026-09-23.
"""
import csv
import pathlib

import numpy as np

SRC = pathlib.Path(__file__).resolve().parents[1] / "results"
OUT = pathlib.Path(__file__).resolve().parents[1] / "tables"


def one(name):
    rows = list(csv.DictReader(open(SRC / name)))
    if len(rows) != 1:
        raise SystemExit(f"{name}: expected one row, found {len(rows)}")
    return rows[0]


s, c = one("p3mimic_suite.csv"), one("p3mimic_ceiling.csv")
seeds = np.array([float(r["het_excess"]) for r in csv.DictReader(open(SRC / "p3mimic_hexc_seeds.csv"))])
f = lambda k: float(s[k])
vals = [("PmN", f"{int(f('n')):,}"), ("PmD", f"{int(f('d'))}"),
        ("PmIota", f"{f('iota'):+.3f}"), ("PmHexc", f"{f('het_excess'):+.3f}"),
        ("PmCov", f"{f('cov30'):.2f}"),
        ("PmImpute", f"{f('tuned_impute'):.4f}"), ("PmIndicator", f"{f('tuned_indicator'):.4f}"),
        ("PmAdaptive", f"{f('safe_adaptive'):.4f}"), ("PmOracle", f"{f('safe_oracle'):.4f}"),
        ("PmDelta", f"{f('delta'):+.4f}"), ("PmWins", f"{int(f('wins'))}"),
        ("PmFolds", f"{int(f('n_folds'))}"),
        ("PmCeilReal", f"{float(c['ceiling_real']):+.4f}"), ("PmCeilPerm", f"{float(c['perm_mean']):+.4f}"),
        ("PmCeilExcess", f"{float(c['excess']):+.4f}"), ("PmCeilP", f"{float(c['p']):.2f}"),
        # sd with ddof=0, the convention of the paper's other +/- figures
        ("PmHexcSeedMean", f"{seeds.mean():+.2f}"), ("PmHexcSeedSd", f"{seeds.std():.2f}"),
        ("PmHexcSeeds", f"{len(seeds)}")]
with open(OUT / "p3mimic.tex", "w") as fh:
    fh.write("% GENERATED by figures/make_p3mimic_table.py from results/p3mimic_suite.csv, "
             "results/p3mimic_ceiling.csv and results/p3mimic_hexc_seeds.csv (prereg/P3MIMIC.md) -- do not edit\n")
    for k, v in vals:
        fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(f"p3mimic.tex written ({len(vals)} macros); het_excess over {len(seeds)} seeds "
      f"{seeds.mean():+.3f} +/- {seeds.std():.3f}")
