"""Emit tables/gendesign.tex and tables/gendesign_counts.tex from the committed GENDESIGN results.

GENDESIGN (prereg/GENDESIGN.md) replaces the on/off control with a dose: rho is the fraction of
the realised coefficient divergence allowed to generate the label. Nothing in the paper's
dose-response paragraph is typed by hand. Run from the paper directory:
    ../paper-plco-hypergraph/.venv/bin/python figures/make_gendesign_table.py
"""
import glob, pathlib, pandas as pd

SRC = pathlib.Path(__file__).resolve().parents[1] / "results" / "gendesign"
OUT = pathlib.Path(__file__).resolve().parents[1] / "tables"

fs = sorted(glob.glob(str(SRC / "*.csv")))
if not fs:
    raise SystemExit(f"no GENDESIGN results in {SRC}")
d = pd.concat([pd.read_csv(f) for f in fs], ignore_index=True)
mix, flat = d[d.outcome_from == "mix"], d[d.outcome_from == "shared_flat"]
g = mix.pivot_table(index="het", columns="rho", values="delta_vs_tuned_ind", aggfunc="mean")
sp = mix.pivot_table(index="het", columns="rho", values="coef_spread", aggfunc="mean")
rhos = sorted(g.columns)
hi, lo = max(g.index), min(g.index)

with open(OUT / "gendesign.tex", "w") as f:
    f.write("% generated by figures/make_gendesign_table.py -- do not edit\n")
    f.write("\\begin{tabular}{r" + "r" * len(rhos) + "}\n\\toprule\n")
    f.write("& \\multicolumn{" + str(len(rhos)) + "}{c}{$\\rho$, the fraction of the divergence that generates the label} \\\\\n")
    f.write("slope heterogeneity & " + " & ".join(f"${r:g}$" for r in rhos) + " \\\\\n\\midrule\n")
    for h in sorted(g.index):
        f.write(f"${h:.1f}$ & " + " & ".join(f"${g.loc[h, r]:+.4f}$" for r in rhos) + " \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")

# the largest relative movement of the realised divergence across rho, within any single cell
cell = ["mechanism", "het", "info", "concentration", "n"]
w = mix.pivot_table(index=cell, columns="rho", values="coef_spread")
rel = float(((w.max(axis=1) - w.min(axis=1)) / w.max(axis=1).abs()).max())

vals = [("GdCells", int(len(mix) // len(rhos))), ("GdArms", len(rhos)),
        ("GdHet", f"{hi:.1f}"),
        ("GdZero", f"{g.loc[hi, 0.0]:+.4f}"), ("GdQuarter", f"{g.loc[hi, 0.25]:+.4f}"),
        ("GdHalf", f"{g.loc[hi, 0.5]:+.4f}"), ("GdThreeQ", f"{g.loc[hi, 0.75]:+.4f}"),
        ("GdOne", f"{g.loc[hi, 1.0]:+.4f}"),
        ("GdRange", f"{g.loc[hi, 1.0] - g.loc[hi, 0.0]:+.4f}"),
        ("GdFlatHet", f"{g.loc[lo, 1.0]:+.4f}"),
        # a sentence ending, not a bare number: the value is exactly zero, and
        # the old f"{rel:.0e}" printed that as "0e+00" in the prose
        ("GdSpreadMove", "does not move at all across the arms, to the last bit" if rel == 0 else
         "moves across the arms by at most a relative $%s\\times 10^{%d}$"
         % tuple((lambda m, e: (m, int(e)))(*f"{rel:.1e}".split("e")))),
        ("GdIntercept", f"{flat.delta_vs_tuned_ind.mean():+.4f}")]
with open(OUT / "gendesign_counts.tex", "w") as f:
    f.write("% generated by figures/make_gendesign_table.py -- do not edit\n")
    for k, v in vals:
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(f"gendesign.tex ({len(g.index)} rows) and gendesign_counts.tex ({len(vals)} macros) written")
print(f"  dose at het={hi}: " + ", ".join(f"{g.loc[hi, r]:+.4f}" for r in rhos))
print(f"  divergence moves across rho by at most {rel:.0e} within a cell; intercept-only arm {flat.delta_vs_tuned_ind.mean():+.4f}")
